FROM node:16.16.0-alpine3.11

# Create app directory
# WORKDIR /usr/nodeapp  

# COPY ./package*.json ./

# COPY . .

# RUN apk update && apk upgrade

# RUN npm install

# RUN apk add --update docker openrc

# CMD [ "npm", "run", "start" ]